# Generated by Django 4.0.4 on 2022-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('address_info', models.CharField(max_length=300)),
                ('phoneno', models.CharField(max_length=300)),
                ('time', models.TextField()),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
